apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: hungerwings-com-tls
spec:
  secretName: hungerwings-com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: hungerwings.com
  dnsNames:
    - hungerwings.com
    - www.hungerwings.com
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - hungerwings.com
          - www.hungerwings.com
